name 'CookbookRubyRails'
maintainer 'Stacey Vetzal'
maintainer_email 'stacey@mojility.ca'
license 'MIT'
description 'Set up a basic Ruby/Rails runtime environment for simple projects'
long_description 'Set up a basic Ruby/Rails runtime environment for simple projects'
version '0.9.0'
